config/routes.rb
Instacheat::Application.routes.draw do

  resources :followers do
    collection do
      get 'remove_excess_followto'
      get 'test'
    end
    
    member do
      get 'dolike'
      get 'like_recent'
      post 'add_followme'
      post 'add_followto'
    end
  end

  resources :users, :only => [:index]
  
  match 'session/connect', :to => 'sessions#connect'
  match 'session/callback', :to => 'sessions#callback'
  match 'login', :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

  root :to => "sessions#new"

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  validates_uniqueness_of :i_id
  
  attr_accessible :followme, :followto, :i_id
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :i_id
  
  attr_accessible :i_id, :i_name, :profile_picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected
    
    def authorize
      if session[:access_token].nil?
        redirect_to :controller => 'sessions', :action => 'new'
      end
    end
end

app/controllers/followers_controller.rb
require "instagram"

class FollowersController < ApplicationController
  before_filter :authorize
  
  # GET /followers
  # GET /followers.json
  def index
    @followme = Follower.find(:all, :conditions => ["followme=?", true])
    @followto = Follower.find(:all, :conditions => ["followto=?", true])
    
    @random_follower = @followto.sample(1).first.i_id
    
    @user_id = session[:i_id]
    @token = session[:access_token]

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /followers/1
  # GET /followers/1.json
  def show
    @follower = Follower.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/new
  # GET /followers/new.json
  def new
    @follower = Follower.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/1/edit
  def edit
    @follower = Follower.find(params[:id])
  end

  # POST /followers
  # POST /followers.json
  def create
    @follower = Follower.new(params[:follower])

    respond_to do |format|
      if @follower.save
        format.html { redirect_to @follower, notice: 'Follower was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /followers/1
  # PUT /followers/1.json
  def update
    @follower = Follower.find(params[:id])

    respond_to do |format|
      if @follower.update_attributes(params[:follower])
        format.html { redirect_to @follower, notice: 'Follower was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /followers/1.js
  def destroy
    @follower = Follower.find(params[:id])
    Instagram.unfollow_user(@follower.i_id, access_token: session[:access_token])
    @follower.destroy

    respond_to do |format|
      format.js
    end
  end
  
  
  def add_followme
    @follower = Follower.find_by_i_id(params[:id])
    if @follower
      @follower.followme = true
      @follower.save
    else
      Follower.create(:followto => false, :followme => true, :i_id => params[:id])
    end
    
    respond_to do |format|
      format.js { render :nothing => true }
    end
  end
  
  def add_followto
    @follower = Follower.find_by_i_id(params[:id])
    if @follower
      @follower.followto = true
      @follower.save
    else
      Follower.create(:followme => false, :followto => true, :i_id => params[:id])
    end
    
    respond_to do |format|
      format.js { render :nothing => true }
    end
  end
  
  
  def remove_excess_followto  
    @excess_followers = Follower.where("followto = ? AND followme = ?", true, false)
    
    respond_to do |format|
      format.js
    end
  end
  
  def like_recent
    followto = Follower.find(:all, :conditions => ["followto=?", true])
    @random_follower = followto.sample(1).first.i_id
    
    @user_recent_media = Instagram.user_recent_media(params[:id], :access_token => session[:access_token]).data
    
    
    respond_to do |format|
      format.js
    end
  end
  
  
  def dolike
    Instagram.like_media(params[:id], :access_token => session[:access_token])
    
    respond_to do |format|
      format.js { render :nothing => true }
    end
  end
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  def test
    client = Instagram.client
    @tag = 'cats'
    @tagged_media = client.tag_recent_media(@tag, count: 1)
    
    for i in 1..30
      @max_tag_id = @tagged_media.pagination.next_max_tag_id
      @tagged_media +=  client.tag_recent_media(@tag, count: 1, max_id: @max_tag_id)
    end
    


    
    respond_to do |format|
      format.html
    end
  end
  
  
  
  
  
  
  
  
  
  
  
  
end

app/controllers/sessions_controller.rb
require "instagram"

class SessionsController < ApplicationController
  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => CALLBACK_URL, :scope => 'likes comments relationships')
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL)
    @user = User.find_by_i_id(response.user.id)
    session[:access_token] = response.access_token
    if @user
      session[:i_id] = @user.i_id
    else
      session[:i_id] = response.user.id 
      @user = User.create(:i_id => response.user.id, :i_name => response.user.username, :profile_picture => response.user.profile_picture)
    end
    
    redirect_to :controller => 'users', :action => 'index'
  end
  
  def new
    if !session[:access_token].nil?
      redirect_to :controller => 'users', :action => 'index'
    else    
      respond_to do |format|
        format.html
      end
    end
  end
  
  def destroy
    session[:access_token] = nil
    redirect_to :controller => 'sessions', :action => 'new'
  end
end

app/controllers/users_controller.rb
require "instagram"

class UsersController < ApplicationController
  before_filter :authorize
  
  # GET /users
  def index
    @users = User.all

    client = Instagram.client(:access_token => session[:access_token])
    @user = client.user


    respond_to do |format|
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followers/_form.html.erb
<%= form_for(@follower) do |f| %>
  <% if @follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
      <% @follower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :i_id %><br />
    <%= f.number_field :i_id %>
  </div>
  <div class="field">
    <%= f.label :followto %><br />
    <%= f.check_box :followto %>
  </div>
  <div class="field">
    <%= f.label :followme %><br />
    <%= f.check_box :followme %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followers/destroy.js.erb
<% if @follower.errors %>
// alert('error!');
<% else %>
// alert('ok!');
<% end %>

app/views/followers/edit.html.erb
<h1>Editing follower</h1>

<%= render 'form' %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

app/views/followers/index.html.erb
<h1>Listing followers</h1>
<p>followme = <%= @followme.size %></p>
<p>
	followto = <%= @followto.size %>
	<%= link_to "поставить лайки", like_recent_follower_path(@random_follower), :class => 'btn', :remote => true %>
</p>




<br />

<%= link_to "Актуализировать followto", '#', :class => 'btn', :id => 'actualize_followto' %>
<%= link_to "Актуализировать followme", '#', :class => 'btn', :id => 'actualize_followme' %>
<hr />
<%= link_to "Лишние", remove_excess_followto_followers_path, :class => 'btn', :remote => true %>



<% content_for :custom_js_bottom do %>
<script>

$('a#actualize_followto').click(function(){
	actualize_followto('https://api.instagram.com/v1/users/<%= @user_id %>/follows?access_token=<%= @token %>&count=100', 0);
	return false;	
});


function actualize_followto(next_url, count) {
	$.ajax({
		method: "GET",
		url: next_url,
		dataType: "jsonp",
		jsonp: "callback",
		jsonpCallback: "jsonpcallback",
		success: function(data){
			$.each(data.data, function(i, item){
				var data = new Object();
				sendData(data, "POST", "/followers/" + item.id + "/add_followto");
			});
			if(data.pagination.next_url && count <= 500){
				actualize_followto(data.pagination.next_url, ++count);
			}
		},
		error: function(jqXHR, textStatus, errorThrown){
			alert('error!!');
		}
	});
}


$('a#actualize_followme').click(function(){
	actualize_followme('https://api.instagram.com/v1/users/<%= @user_id %>/followed-by?access_token=<%= @token %>&count=100', 0);
	return false;	
});


function actualize_followme(next_url, count) {
	$.ajax({
		method: "GET",
		url: next_url,
		dataType: "jsonp",
		jsonp: "callback",
		jsonpCallback: "jsonpcallback",
		success: function(data){
			$.each(data.data, function(i, item){
				var data = new Object();
				sendData(data, "POST", "/followers/" + item.id + "/add_followme");
			});
			if(data.pagination.next_url && count <= 500){
				actualize_followme(data.pagination.next_url, ++count);
			}
		},
		error: function(jqXHR, textStatus, errorThrown){
			alert('error!!');
		}
	});
}


function sendData(data, type, url){
	data['format'] = 'js';
	$.ajax({
		type: type,
		url: url,
		data: data
	});
}







</script>
<% end %>

app/views/followers/like_recent.js.erb
<% count = 0 %>
<% @user_recent_media.each do |media| %>
	<% if [0, 1, 2].sample == 0 %>
		setTimeout(function() {
			doLike("<%= media.id %>");
		}, <%= count*5000 %> + Math.random() * 1000);
		<% count += 1 %>
	<% end %>
<% end %>

setTimeout(function() {
	var data = new Object();
	data['user_id'] = <%= @random_follower %>;
	sendData(data, "GET", "<%= like_recent_follower_path(@random_follower) %>" );
}, <%= count*7000 %>);


function doLike(media_id){
	var data = new Object();
	data['id'] = media_id;
	sendData(data, "GET", "/followers/" + data['id'] + "/dolike" );
}


function sendData(data, type, url){
	data['format'] = 'js';
	$.ajax({
		type: type,
		url: url,
		data: data
	});
}

app/views/followers/new.html.erb
<h1>New follower</h1>

<%= render 'form' %>

<%= link_to 'Back', followers_path %>

app/views/followers/remove_excess_followto.html.erb
<%= @excess_followers.size %>
<hr />
<% @excess_followers.each do |user| %>
<p><%= user.id %></p>
<% end %>

app/views/followers/remove_excess_followto.js.erb
<% count = 0 %>
<% @excess_followers.each do |user| %>
		setTimeout(function() {
		sendTag("<%= user.id %>");
		}, <%= count*7000 %>);
		<% count += 1 %>
<% end %>



function sendTag(user_id){
	var data = new Object();
	data['id'] = user_id;
	sendData(data, "DELETE", "/followers/"+data['id']);
}


function sendData(data, type, url){
	data['format'] = 'js';
	$.ajax({
		type: type,
		url: url,
		data: data
	});
}

app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>I:</b>
  <%= @follower.i_id %>
</p>

<p>
  <b>Followto:</b>
  <%= @follower.followto %>
</p>

<p>
  <b>Followme:</b>
  <%= @follower.followme %>
</p>


<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>

app/views/followers/test.html.erb
<% @tagged_media['data'].each do |media| %>
<img src="<%= media.images.thumbnail.url%>">
<p>Likes: <%= media.likes['count'] %></p>
<p>Comments: <%= media.comments['count'] %></p>
<% end %>


<hr /><hr /><hr /><hr /><hr /><hr /><hr /><hr /><hr /><hr /><hr /><hr />

app/views/layouts/_navigation.html.erb
<% if !session[:access_token].nil? %>
<ul class="nav">
	<li <%= "class='active'" if params[:controller] == 'followers' %>><%= link_to "Подписчики", followers_path %></li>
	<li <%= "class='active'" if params[:controller] == 'users' %>><%= link_to "Пользователи", users_path %></li>
</ul>
<ul class="nav pull-right">
	<li>
		<%= link_to "logout", logout_path %>
	</li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
	<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>instacheat</title>
    <%= csrf_meta_tags %>
		
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->


		
		<%= stylesheet_link_tag "application", :media => "all" %>
		<!-- [if IE]>
		    <link rel="stylesheet" type="text/css" href="font-awesome-ie7.css" />
		<![endif]-->		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<%= javascript_include_tag "application" %>
		<%= yield :custom_js_top %>
  </head>
	
	<body id="<%= params[:controller].parameterize %>_controller">
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">
					<%= render 'layouts/navigation' %>
				</div>
			</div>
		</div>
		
		<div class="container">
			<%= yield %>
			<footer>
				<p>&copy; Company 2012</p>
			</footer>
		</div>

		<%= yield :custom_js_bottom %>
  </body>
</html>

app/views/users/index.html.erb
<%= debug session %>

<hr />
<%= @user.id %>

<h1>Listing users</h1>

<table>
  <tr>
    <th>Id</th>
    <th>name</th>
    <th>Profile picture</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.i_id %></td>
    <td><%= user.i_name %></td>
		<td><%= image_tag user.profile_picture  %></td>
  </tr>
<% end %>
</table>

<br />